class ChargesController < ApplicationController

	def new
	end

	def create
		@amount = 500 #in cents, so $5

		customer = Stripe::Customer.create(
			:email => params[:stripeEmail],
			:card => params[:stripeToken] #auto generated by Checkout
		)

		charge = Stripe::Charge.create(
			:customer => customer.id,
			:amount => @amount,
			:description => 'Rails Stripe Customer',
			:currency => 'usd'
		)
	
		redirect_to post_path(params[:post_id])
		
		rescue Stripe::CardError => e
			flash[:error] = e.message
			redirect_to post_path(params[:post_id]) 
	end
end
