class PaymentsController < ApplicationController
	before_action :save_customer_id, only: [:create]
	before_action :book_post, only: [:create]
	
	def index
		@users = User.includes(:payments).where(payments: {paid: false})
	end

	def create
		date = params[:start_lease].to_date
		begin 
			while(date <= params[:end_lease].to_date)
				payment = Payment.create(due: date, amount: params[:amount], user_id: current_user.id)
				current_user.payments << payment
				date = date.next_month
			end
			redirect_to payment_success_path
		rescue Exception => e
			puts "ERRRRROOOORRRRR"
			puts e.message
			redirect_to  root_path
		end
	end

	private
	
	def payment_params
		params.require(:payment).permit(:due, :amount)
	end

	def save_customer_id
		customer = Stripe::Customer.create(
			:email => params[:stripeEmail],
			:card => params[:stripeToken] #auto generated by Checkout
		)
		current_user.save_customer_id(customer.id)
	end

	def book_post
		@post = Post.find(params[:post_id])
		@post.book!
	end
end
