class PaymentsController < ApplicationController

	def index
		@users = User.includes(:payments).where(payments: {paid: false})
	end

	def create
	  customer = Stripe::Customer.create(
			:email => params[:stripeEmail],
			:card => params[:stripeToken] #auto generated by Checkout
		)
		current_user.save_customer_id(customer.id)
		
		date = params[:start_lease].to_date
	
		while(date <= params[:end_lease].to_date)
			payment = Payment.create(due: date, amount: params[:amount], user_id: current_user.id)
			current_user.payments << payment
			date = date.next_month
		end
		redirect_to root_path
	end

	private
	
	def payment_params
		params.require(:payment).permit(:due, :amount)
	end
end
